version: '3.8'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-server-container
    environment:
      SA_PASSWORD: YourStrongPassword!   # Change this to a strong password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
